feat(collections): add schema duration to collection
viaacode/hetarchief-proxy pull request #272
Opened 2023-01-19 13:15 UTC by tourlbr

2023-01-19 13:55 UTC, WardVerc1 approved these changes

2023-01-19 16:10 UTC, bertyhell requested changes

2023-01-19 17:30 UTC, tourlbr commented on src/modules/collections/types.ts
> +	duration: string;
Adjusted

2023-01-23 10:25 UTC, bertyhell approved these changes

2023-01-23 12:04 UTC, merged