feat(arc-1336): create apply license for esquery func
viaacode/hetarchief-proxy pull request #285
Opened 2023-02-07 16:01 UTC by tourlbr

- Apply licensing criteria to elastic search query
- Get active visitor requests by user to retrieve spaces and folders
- General cleanup
- Extensions to existing functionality

2023-02-08 17:03 UTC, bertyhell requested changes

2023-02-10 09:02 UTC, bertyhell requested changes

2023-02-10 09:02 UTC, bertyhell commented on src/modules/ie-objects/ie-objects.conts.ts
> +		...IE_OBJECT_PROPS_METADATA_SET_ESSENCE,
![image](https://user-images.githubusercontent.com/1710840/218048516-a62df8c4-b055-46cf-846b-5b5f5d82c726.png)

2023-02-10 16:33 UTC, tourlbr commented on src/modules/ie-objects/elasticsearch/queryBuilder.ts
> +			},
@bertyhell Elastic search laat dit niet toe
![Screenshot 2023-02-10 at 17 31 45](https://user-images.githubusercontent.com/37472626/218145171-a0493c66-ad81-4ae1-b40e-11643d93e80f.png)

2023-02-10 16:37 UTC, tourlbr commented on src/modules/ie-objects/elasticsearch/queryBuilder.ts
> +			},
@bertyhell geeft issues met die ids
![Screenshot 2023-02-10 at 17 37 18](https://user-images.githubusercontent.com/37472626/218146070-dbd84faa-3f14-465e-a5fa-928ea7122f32.png)

2023-02-13 12:35 UTC, bertyhell approved these changes

2023-02-13 12:35 UTC, bertyhell commented on src/modules/ie-objects/controllers/ie-objects.controller.ts
>  		);
This function only needs sector to fetch the info, so we should only pass sector to the function.

2023-02-13 12:35 UTC, bertyhell commented on src/modules/ie-objects/controllers/ie-objects.controller.ts
> +		}
It might be useful to also select sector when the user is first logged in, so the sector is always available on the session user object.

2023-02-13 12:35 UTC, bertyhell commented on src/modules/ie-objects/helpers/limit-access-to-object-details.ts
> +		// folders -> if ie object id is in here than the user has folder access to this vistor space
```suggestion
		// folders -> if ie object id is in here then the user has folder access to this visitor space
```

2023-02-13 12:35 UTC, bertyhell commented on src/modules/ie-objects/controllers/ie-objects.controller.ts
> +		}
https://github.com/viaacode/hetarchief-proxy/blob/master/src/modules/auth/controllers/het-archief.controller.ts#L128-L130

2023-02-13 12:53 UTC, merged