Feature/arc 1425 object to csv
viaacode/hetarchief-proxy pull request #318
Opened 2023-03-06 13:49 UTC by EmileVanTichelenSHD

https://meemoo.atlassian.net/browse/ARC-1425

New packages: papaparse, flat

2023-03-06 15:30 UTC, tourlbr requested changes
Don't forget to write tests for the code you have written.

2023-03-06 15:30 UTC, tourlbr commented on package.json
> +    "flat": "^5.0.2",
REQ: remove flat npm package

2023-03-06 15:30 UTC, tourlbr commented on src/modules/ie-objects/controllers/ie-objects.controller.ts
> +			limitAccessToObjectDetails(objectMetadata, {
REQ: both csv and xml should not be using **limitAccessToObjectDetails**

2023-03-06 15:30 UTC, tourlbr commented on src/modules/ie-objects/helpers/convert-objects-to-csv.ts
> +export const convertObjectsToCsv = (objects: Partial<IeObject>[]): string => {
REQ: test file needs to be written with several usecase to be sure the code works as intended. Example can be found in convert to xml spec file.

2023-03-06 15:30 UTC, tourlbr commented on src/modules/ie-objects/helpers/convert-objects-to-xml.ts
>  export const convertObjectsToXml = (objects: Partial<IeObject>[]): string => {
Q: was the spec file reviewed after these code changes to be sure they still succeed?
REQ: review test case and update were necessary

2023-03-07 13:22 UTC, tourlbr approved these changes
I'm going to pre approve this but please the necessary code based on the comments I left behind.

2023-03-07 13:22 UTC, tourlbr commented on src/modules/ie-objects/helpers/convert-objects-to-csv.ts
> +import { flatten } from 'flat'; //toch flat gebruiken
REQ: remove comment

2023-03-07 13:22 UTC, tourlbr commented on src/modules/ie-objects/helpers/convert-objects-to-xml.ts
> +	// const { accessThrough, ...xmlData } = object;
REQ: remove unused line

2023-03-07 13:22 UTC, tourlbr commented on src/modules/ie-objects/services/ie-objects.service.ts
> +	 * Get the objeµt detail fields that are exposed as metadata
REQ: fix typo

2023-03-08 09:51 UTC, bertyhell requested changes

2023-03-08 09:51 UTC, bertyhell commented on src/modules/ie-objects/ie-objects.conts.ts
> +	//ebucore_is_media_fragment_of => Not currently available in DB
These values are indeed not available yet, but i don't think the code breaks if you enable these, right?
If so we should enable them, that way we don't have to touch this code anymore once those fields become available and the export will just work as expected.

2023-03-08 09:51 UTC, bertyhell commented on src/modules/ie-objects/helpers/convert-objects-to-csv.spec.ts
> +		console.log(csv);
Remove this console.log

2023-03-08 09:51 UTC, bertyhell commented on package.json
> +    "ramda": "^0.28.0",
don't add ramda since we already use lodash in this repository

2023-03-08 14:28 UTC, bertyhell approved these changes

2023-03-09 08:46 UTC, merged