feat(arc-1480): return search terms from boolean search query
viaacode/hetarchief-proxy pull request #331
Opened 2023-03-13 14:30 UTC by bertyhell

https://meemoo.atlassian.net/browse/ARC-1480

http://localhost:3100/docs/#/Ie%20Objects/IeObjectsController_getIeObjects

![image](https://user-images.githubusercontent.com/1710840/224732469-390b84cf-2289-47ef-8eb4-1e6e5429b97e.png)

![image](https://user-images.githubusercontent.com/1710840/224732499-0e98983e-44b1-4453-8fb0-458e25562fa6.png)

2023-03-13 15:16 UTC, tourlbr requested changes

2023-03-13 15:16 UTC, tourlbr commented on src/modules/ie-objects/helpers/convert-node-to-es-query-filter-objects.spec.ts
>  describe('Convert node to es query filter objects', () => {
REQ: fix tests

3 tests are failing including scenario where `minimum_should_match equals 9` please fix

![Screenshot 2023-03-13 at 16 11 58](https://user-images.githubusercontent.com/37472626/224744364-8ae85553-3836-4b57-a208-8ceca709649a.png)
![Screenshot 2023-03-13 at 16 12 06](https://user-images.githubusercontent.com/37472626/224744368-f8f3d459-d83e-4ba0-a245-ee533946be7b.png)
![Screenshot 2023-03-13 at 16 12 13](https://user-images.githubusercontent.com/37472626/224744374-c51faa75-9628-413b-8bc2-d5527329229e.png)

2023-03-14 07:38 UTC, WardVerc1 approved these changes

2023-03-14 14:00 UTC, bertyhell commented on src/modules/ie-objects/helpers/convert-node-to-es-query-filter-objects.spec.ts
> -(jsep as any).removeAllBinaryOps();
you're right, i was intending to remove these from the src/modules/ie-objects/helpers/convert-string-to-search-terms.spec.ts file instead.
fixed

2023-03-14 14:02 UTC, bertyhell commented
Test Suites: 62 passed, 62 total
Tests:       476 passed, 476 total
Snapshots:   0 total
Time:        61.051 s
Ran all test suites.

2023-03-14 14:46 UTC, tourlbr approved these changes

2023-03-14 15:14 UTC, silkederudder-shd approved these changes

2023-03-14 16:54 UTC, merged