Feature/arc 1500 request list tests
viaacode/hetarchief-proxy pull request #346
Opened 2023-03-21 15:12 UTC by EmileVanTichelenSHD

https://meemoo.atlassian.net/browse/ARC-1500

I also changed some things from send request list to make it cleaner / more optimized.

2023-03-21 15:16 UTC, tourlbr requested changes

2023-03-21 15:16 UTC, tourlbr commented on src/modules/campaign-monitor/services/campaign-monitor.service.spec.ts
> +	const env = process.env;
REQ: this should no longer be required so please remove this.

2023-03-21 15:16 UTC, tourlbr commented on src/modules/campaign-monitor/services/campaign-monitor.service.spec.ts
> +		process.env = { ...env };
REQ: this should no longer be required so please remove this.

2023-03-21 15:26 UTC, tourlbr approved these changes

2023-03-22 10:10 UTC, tourlbr requested changes

2023-03-22 10:10 UTC, tourlbr commented on src/modules/campaign-monitor/templates/templates.service.ts
> +export class TemplateService {
REQ: You can just do similar logic as you dit with xml & csv. No need for Class.

2023-03-22 14:25 UTC, tourlbr approved these changes

2023-03-23 12:24 UTC, bertyhell approved these changes

2023-03-23 12:30 UTC, bertyhell requested changes

2023-03-23 12:30 UTC, bertyhell commented on src/modules/campaign-monitor/services/campaign-monitor.service.ts
> +	): Promise<void | BadRequestException | boolean> {
We shouldn't add exceptions in the return type
```suggestion
	): Promise<boolean> {
```

2023-03-23 13:39 UTC, bertyhell requested changes

2023-03-23 18:02 UTC, merged