fix(arc-1834): do not show object with license if no keyuser
viaacode/hetarchief-proxy pull request #440
Opened 2023-06-27 09:07 UTC by WardVerc1

Ticket: https://meemoo.atlassian.net/browse/ARC-1834

2023-06-28 06:21 UTC, SHDBramVandenbussche approved these changes

2023-06-30 09:08 UTC, bertyhell requested changes

2023-06-30 09:08 UTC, bertyhell commented on src/modules/collections/controllers/collections.controller.ts
> +				}
i think this does the same thing:
Also best to always return only booleans in a filter function, not undefined or objects
```suggestion
				const hasOnlyIntraCpLicenses =
					(object.licenses || []).filter(license => 
						![IeObjectLicense.INTRA_CP_CONTENT, IeObjectLicense.INTRA_CP_METADATA_ALL].includes(license)
					).length === 0;

				if (!isKeyUser && hasOnlyIntraCpLicenses) {
					return false;
				} else {
					return true;
				}
```

2023-06-30 10:22 UTC, bertyhell approved these changes

2023-06-30 13:01 UTC, merged